/**
 * Clawflare CLI - config command
 * Wrangler configuration generation and management
 */

import { execSync } from "child_process";
import * as fs from "fs/promises";
import * as path from "path";
import {
  loadConfigFromCwd,
  getWorkerName,
  getWorkflowName,
  getDatabaseName,
  getCompatibilityDate,
  ConfigValidationError,
} from "../lib/load-project-config.js";

export interface WranglerConfig {
  name: string;
  compatibility_date: string;
  compatibility_flags: string[];
  main: string;
  minify?: boolean;
  define?: Record<string, string>;
  services?: Array<{
    binding: string;
    service: string;
    entrypoint: string;
  }>;
  worker_loaders?: Array<{
    binding: string;
  }>;
  d1_databases: Array<{
    binding: string;
    database_name: string;
    database_id: string;
    preview_database_id?: string;
    migrations_dir?: string;
  }>;
  durable_objects: {
    bindings: Array<{
      name: string;
      class_name: string;
    }>;
  };
  migrations: Array<{
    tag: string;
    new_classes?: string[];
    new_sqlite_classes?: string[];
    deleted_classes?: string[];
  }>;
  workflows: Array<{
    name: string;
    binding: string;
    class_name: string;
  }>;
  containers?: Array<{
    class_name: string;
    image: string;
    max_instances?: number;
    instance_type?: string;
  }>;
  vars?: Record<string, string>;
}

export interface WranglerConfigGeneratorOptions {
  projectDir: string;
  projectName: string;
  dbId?: string;
  dbName: string;
  dbPreviewId?: string;
  workerName?: string;
  workflowName?: string;
  accountId?: string;
  compatibilityDate?: string;
  aiProvider?: string;
  aiModel?: string;
}

/**
 * Generate Wrangler configuration matching the actual runtime requirements
 */
export async function generateWranglerConfig(
  options: WranglerConfigGeneratorOptions & { outputPath?: string }
): Promise<string> {
  const {
    projectDir,
    projectName,
    dbId = "<database-id>",
    dbName,
    dbPreviewId,
    workerName = projectName,
    workflowName = `${workerName}-workflow`,
    compatibilityDate = "2025-01-01",
    aiProvider = "amazon-bedrock",
    aiModel = "minimax.minimax-m2.5",
  } = options;

  const config: WranglerConfig = {
    name: workerName,
    compatibility_date: compatibilityDate,
    compatibility_flags: ["nodejs_compat", "enable_ctx_exports"],
    main: "./src/index.ts",
    minify: true,
    define: {
      "process.env.NODE_ENV": '"production"',
      __DEV__: "false",
    },
    services: [
      {
        binding: "HTTP_GATEWAY",
        service: workerName,
        entrypoint: "HttpGateway",
      },
    ],
    worker_loaders: [
      {
        binding: "LOADER",
      },
    ],
    d1_databases: [
      {
        binding: "DB",
        database_name: dbName,
        database_id: dbId,
        preview_database_id: dbPreviewId || dbId,
        migrations_dir: "migrations",
      },
    ],
    durable_objects: {
      bindings: [
        {
          name: "WEBSOCKET_SESSION",
          class_name: "ClawflareWebSocketSession",
        },
        {
          name: "CODING_CONTAINER",
          class_name: "CodingContainer",
        },
      ],
    },
    migrations: [
      {
        tag: "v1",
        new_sqlite_classes: ["ClawflareDatastore"],
      },
      {
        tag: "v2",
        new_classes: ["ClawflareWebSocketSession"],
      },
      {
        tag: "v3",
        deleted_classes: ["ClawflareDatastore"],
      },
      {
        tag: "v4",
        new_sqlite_classes: ["CodingContainer"],
      },
    ],
    workflows: [
      {
        name: workflowName,
        binding: "AGENT_WORKFLOW",
        class_name: "PersistentSessionWorkflow",
      },
    ],
    containers: [
      {
        class_name: "CodingContainer",
        image: "./container-runtime/Dockerfile",
        max_instances: 10,
        instance_type: "standard-2",
      },
    ],
    vars: {
      AI_PROVIDER: aiProvider,
      AI_MODEL: aiModel,
    },
  };

  // Determine output path
  const outputPath = options.outputPath ?? path.join(projectDir, ".clawflare", "wrangler.jsonc");

  const output = `// Generated by Clawflare. Do not edit directly.
// Source of truth: clawflare.config.ts
${JSON.stringify(config, null, 2)}
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, output);

  return outputPath;
}

interface ConfigGenerateOptions {
  env?: string;
  output?: string;
}

interface CloudflareState {
  accountId?: string;
  d1DatabaseId?: string;
  previewDatabaseId?: string;
}

interface StateFile {
  version: number;
  cloudflare?: CloudflareState;
}

async function loadState(projectDir: string): Promise<StateFile | null> {
  try {
    const statePath = path.join(projectDir, ".clawflare", "state.json");
    const content = await fs.readFile(statePath, "utf-8");
    return JSON.parse(content) as StateFile;
  } catch {
    return null;
  }
}

async function getCloudflareAccountId(): Promise<string | null> {
  try {
    const result = execSync("wrangler whoami", { encoding: "utf-8" });
    const match = result.match(/Account ID\s+([a-f0-9]+)/i);
    if (match) return match[1];

    const configPath = path.join(process.env.HOME || "", ".wrangler", "config.json");
    const configContent = await fs.readFile(configPath, "utf-8");
    const config = JSON.parse(configContent);
    if (config.accounts && config.accounts.length > 0) {
      return config.accounts[0].id;
    }

    return null;
  } catch {
    return null;
  }
}

/**
 * Generate command - creates the Wrangler configuration file
 */
export async function configGenerateCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Load real config
  let loadedConfig;
  try {
    loadedConfig = await loadConfigFromCwd();
  } catch (error) {
    if (error instanceof ConfigValidationError) {
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }

  const config = loadedConfig.config;

  console.log(`Generating Wrangler config for "${config.name}"...`);

  // Load state with proper typing
  const emptyState: StateFile = { version: 1, cloudflare: {} };
  const state: StateFile = (await loadState(cwd)) || emptyState;

  // Get account ID
  const accountId = await getCloudflareAccountId();
  if (accountId) {
    if (!state.cloudflare) state.cloudflare = {};
    state.cloudflare.accountId = accountId;
  }

  // Determine names using config-derived functions
  const workerName = getWorkerName(config, options.env);
  const workflowName = getWorkflowName(config, options.env);
  const dbName = getDatabaseName(config, options.env);
  const compatibilityDate = getCompatibilityDate(config);
  const dbId = state.cloudflare?.d1DatabaseId;
  const dbPreviewId = state.cloudflare?.previewDatabaseId;

  // Generate config with explicit output path
  const outputPath = options.output || path.join(cwd, ".clawflare", "wrangler.jsonc");
  await generateWranglerConfig({
    projectDir: cwd,
    projectName: config.name,
    dbId,
    dbName,
    dbPreviewId,
    workerName,
    workflowName,
    accountId: accountId || undefined,
    compatibilityDate,
    aiProvider: config.ai?.provider,
    aiModel: config.ai?.model,
    outputPath,
  });

  console.log(`✓ Generated: ${outputPath}`);
  console.log(`\nDatabase: ${dbName}`);
  console.log(`Worker: ${workerName}`);
  console.log(`Workflow: ${workflowName}`);
  if (dbId) {
    console.log(`Database ID: ${dbId}`);
  } else {
    console.log(`Database ID: (not set - will be created on deploy)`);
  }
}

/**
 * Print command - displays the generated Wrangler configuration
 */
export async function configPrintCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Load real config
  let loadedConfig;
  try {
    loadedConfig = await loadConfigFromCwd();
  } catch (error) {
    if (error instanceof ConfigValidationError) {
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }

  const config = loadedConfig.config;

  // Load state with proper typing
  const emptyState: StateFile = { version: 1, cloudflare: {} };
  const state: StateFile = (await loadState(cwd)) || emptyState;

  // Get account ID
  const accountId = await getCloudflareAccountId();

  // Determine names using config-derived functions
  const workerName = getWorkerName(config, options.env);
  const workflowName = getWorkflowName(config, options.env);
  const dbName = getDatabaseName(config, options.env);
  const compatibilityDate = getCompatibilityDate(config);
  const dbId = state.cloudflare?.d1DatabaseId;
  const dbPreviewId = state.cloudflare?.previewDatabaseId;

  // Generate config to a temp path
  await fs.mkdir(path.join(cwd, ".clawflare"), { recursive: true });
  const configPath = await generateWranglerConfig({
    projectDir: cwd,
    projectName: config.name,
    dbId,
    dbName,
    dbPreviewId,
    workerName,
    workflowName,
    accountId: accountId || undefined,
    compatibilityDate,
    aiProvider: config.ai?.provider,
    aiModel: config.ai?.model,
  });

  // Read and display
  const content = await fs.readFile(configPath, "utf-8");
  console.log(content);
}

/**
 * Config command handler with subcommands
 */
export async function configCommand(
  subcommand: "generate" | "print",
  options: ConfigGenerateOptions
): Promise<void> {
  if (subcommand === "generate") {
    await configGenerateCommand(options);
  } else if (subcommand === "print") {
    await configPrintCommand(options);
  } else {
    console.error(`Unknown subcommand: ${subcommand}`);
    console.error("Available subcommands: generate, print");
    process.exit(1);
  }
}
