/**
 * Clawflare CLI - config command
 * Wrangler configuration generation and management
 */

import { execSync } from "child_process";
import * as fs from "fs/promises";
import * as path from "path";
import {
  loadConfigFromCwd,
  getWorkerName,
  getDatabaseName,
  getCompatibilityDate,
  ConfigValidationError,
} from "../lib/load-project-config.js";

export interface WranglerConfig {
  name: string;
  compatibility_date: string;
  compatibility_flags: string[];
  main: string;
  build: {
    command: string;
  };
  d1_databases: Array<{
    binding: string;
    database_name: string;
    database_id: string;
  }>;
  durable_objects: {
    bindings: Array<{
      name: string;
      class_name: string;
    }>;
  };
  migrations: Array<{
    tag: string;
    new_classes: string[];
    new_sqlite_classes?: string[];
  }>;
  workflows: Array<{
    name: string;
    class_name: string;
  }>;
  containers?: Array<{
    name: string;
    image: string;
  }>;
  workers?: {
    kv_namespaces?: Array<{
      binding: string;
      id: string;
    }>;
    vars?: Record<string, string>;
  };
}

export interface WranglerConfigGeneratorOptions {
  projectDir: string;
  projectName: string;
  dbId?: string;
  dbName: string;
  workerName?: string;
  accountId?: string;
  compatibilityDate?: string;
}

/**
 * Generate Wrangler configuration
 */
export async function generateWranglerConfig(
  options: WranglerConfigGeneratorOptions
): Promise<string> {
  const {
    projectDir,
    projectName,
    dbId = "<database-id>",
    dbName,
    workerName = projectName,
    compatibilityDate = "2025-01-01",
  } = options;

  const config: WranglerConfig = {
    name: workerName,
    compatibility_date: compatibilityDate,
    compatibility_flags: ["nodejs_compat"],
    main: "./src/index.ts",
    build: {
      command: "npx tsc --noEmit",
    },
    d1_databases: [
      {
        binding: "DB",
        database_name: dbName,
        database_id: dbId,
      },
    ],
    durable_objects: {
      bindings: [
        {
          name: "SESSION_COORDINATOR",
          class_name: "ClawflareSessionCoordinator",
        },
        {
          name: "WEBSOCKET_SESSION",
          class_name: "ClawflareWebSocketSession",
        },
      ],
    },
    migrations: [
      {
        tag: "v1",
        new_classes: ["ClawflareSessionCoordinator", "ClawflareWebSocketSession"],
      },
    ],
    workflows: [
      {
        name: "PERSISTENT_SESSION",
        class_name: "PersistentSessionWorkflow",
      },
    ],
    containers: [
      {
        name: "CodingContainer",
        image: "clawflare/container-runtime:latest",
      },
    ],
  };

  const configPath = path.join(projectDir, ".clawflare", "wrangler.jsonc");
  const output = `// Generated by Clawflare. Do not edit directly.
// Source of truth: clawflare.config.ts
${JSON.stringify(config, null, 2)}
`;

  await fs.mkdir(path.dirname(configPath), { recursive: true });
  await fs.writeFile(configPath, output);

  return configPath;
}

interface ConfigGenerateOptions {
  env?: string;
  output?: string;
}

interface CloudflareState {
  accountId?: string;
  d1DatabaseId?: string;
}

interface StateFile {
  version: number;
  cloudflare?: CloudflareState;
}

async function loadState(projectDir: string): Promise<StateFile | null> {
  try {
    const statePath = path.join(projectDir, ".clawflare", "state.json");
    const content = await fs.readFile(statePath, "utf-8");
    return JSON.parse(content) as StateFile;
  } catch {
    return null;
  }
}

async function getCloudflareAccountId(): Promise<string | null> {
  try {
    const result = execSync("wrangler whoami", { encoding: "utf-8" });
    const match = result.match(/Account ID\s+([a-f0-9]+)/i);
    if (match) return match[1];

    const configPath = path.join(process.env.HOME || "", ".wrangler", "config.json");
    const configContent = await fs.readFile(configPath, "utf-8");
    const config = JSON.parse(configContent);
    if (config.accounts && config.accounts.length > 0) {
      return config.accounts[0].id;
    }

    return null;
  } catch {
    return null;
  }
}

/**
 * Generate command - creates the Wrangler configuration file
 */
export async function configGenerateCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Load real config
  let loadedConfig;
  try {
    loadedConfig = await loadConfigFromCwd();
  } catch (error) {
    if (error instanceof ConfigValidationError) {
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }

  const config = loadedConfig.config;

  console.log(`Generating Wrangler config for "${config.name}"...`);

  // Load state with proper typing
  const emptyState: StateFile = { version: 1, cloudflare: {} };
  const state: StateFile = (await loadState(cwd)) || emptyState;

  // Get account ID
  const accountId = await getCloudflareAccountId();
  if (accountId) {
    if (!state.cloudflare) state.cloudflare = {};
    state.cloudflare.accountId = accountId;
  }

  // Determine names using config-derived functions
  const workerName = getWorkerName(config, options.env);
  const dbName = getDatabaseName(config, options.env);
  const compatibilityDate = getCompatibilityDate(config);
  const dbId = state.cloudflare?.d1DatabaseId;

  // Honor --output option
  const outputPath = options.output || path.join(cwd, ".clawflare", "wrangler.jsonc");

  // Generate config
  await generateWranglerConfig({
    projectDir: path.dirname(outputPath),
    projectName: config.name,
    dbId,
    dbName,
    workerName,
    accountId: accountId || undefined,
    compatibilityDate,
  });

  if (options.output) {
    // If custom output path, we need to copy/modify
    const tempPath = path.join(cwd, ".clawflare", "wrangler.jsonc");
    if (tempPath !== outputPath) {
      const content = await fs.readFile(tempPath, "utf-8");
      await fs.writeFile(outputPath, content);
      await fs.unlink(tempPath);
    }
  }

  const finalPath = options.output || path.join(cwd, ".clawflare", "wrangler.jsonc");
  console.log(`✓ Generated: ${finalPath}`);
  console.log(`\nDatabase: ${dbName}`);
  console.log(`Worker: ${workerName}`);
  if (dbId) {
    console.log(`Database ID: ${dbId}`);
  } else {
    console.log(`Database ID: (not set - will be created on deploy)`);
  }
}

/**
 * Print command - displays the generated Wrangler configuration
 */
export async function configPrintCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Load real config
  let loadedConfig;
  try {
    loadedConfig = await loadConfigFromCwd();
  } catch (error) {
    if (error instanceof ConfigValidationError) {
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }
    throw error;
  }

  const config = loadedConfig.config;

  // Load state with proper typing
  const emptyState: StateFile = { version: 1, cloudflare: {} };
  const state: StateFile = (await loadState(cwd)) || emptyState;

  // Get account ID
  const accountId = await getCloudflareAccountId();

  // Determine names using config-derived functions
  const workerName = getWorkerName(config, options.env);
  const dbName = getDatabaseName(config, options.env);
  const compatibilityDate = getCompatibilityDate(config);
  const dbId = state.cloudflare?.d1DatabaseId;

  // Generate config (to temp path)
  await fs.mkdir(path.join(cwd, ".clawflare"), { recursive: true });
  const configPath = await generateWranglerConfig({
    projectDir: cwd,
    projectName: config.name,
    dbId,
    dbName,
    workerName,
    accountId: accountId || undefined,
    compatibilityDate,
  });

  // Read and display
  const content = await fs.readFile(configPath, "utf-8");
  console.log(content);
}

/**
 * Config command handler with subcommands
 */
export async function configCommand(
  subcommand: "generate" | "print",
  options: ConfigGenerateOptions
): Promise<void> {
  if (subcommand === "generate") {
    await configGenerateCommand(options);
  } else if (subcommand === "print") {
    await configPrintCommand(options);
  } else {
    console.error(`Unknown subcommand: ${subcommand}`);
    console.error("Available subcommands: generate, print");
    process.exit(1);
  }
}
