/**
 * Clawflare CLI - config command
 * Wrangler configuration generation and management
 */

import { execSync } from "child_process";
import * as fs from "fs/promises";
import * as path from "path";

export interface WranglerConfig {
  name: string;
  compatibility_date: string;
  compatibility_flags: string[];
  main: string;
  build: {
    command: string;
  };
  d1_databases: Array<{
    binding: string;
    database_name: string;
    database_id: string;
  }>;
  durable_objects: {
    bindings: Array<{
      name: string;
      class_name: string;
    }>;
  };
  migrations: Array<{
    tag: string;
    new_classes: string[];
    new_sqlite_classes?: string[];
  }>;
  workflows: Array<{
    name: string;
    class_name: string;
  }>;
  containers?: Array<{
    name: string;
    image: string;
  }>;
  workers?: {
    kv_namespaces?: Array<{
      binding: string;
      id: string;
    }>;
    vars?: Record<string, string>;
  };
}

export interface WranglerConfigGeneratorOptions {
  projectDir: string;
  projectName: string;
  dbId?: string;
  dbName: string;
  workerName?: string;
  accountId?: string;
  compatibilityDate?: string;
}

/**
 * Generate Wrangler configuration
 */
export async function generateWranglerConfig(
  options: WranglerConfigGeneratorOptions
): Promise<string> {
  const {
    projectDir,
    projectName,
    dbId = "<database-id>",
    dbName,
    workerName = projectName,
    compatibilityDate = "2025-01-01",
  } = options;

  const config: WranglerConfig = {
    name: workerName,
    compatibility_date: compatibilityDate,
    compatibility_flags: ["nodejs_compat"],
    main: "./src/index.ts",
    build: {
      command: "npx tsc --noEmit",
    },
    d1_databases: [
      {
        binding: "DB",
        database_name: dbName,
        database_id: dbId,
      },
    ],
    durable_objects: {
      bindings: [
        {
          name: "SESSION_COORDINATOR",
          class_name: "ClawflareSessionCoordinator",
        },
        {
          name: "WEBSOCKET_SESSION",
          class_name: "ClawflareWebSocketSession",
        },
      ],
    },
    migrations: [
      {
        tag: "v1",
        new_classes: ["ClawflareSessionCoordinator", "ClawflareWebSocketSession"],
      },
    ],
    workflows: [
      {
        name: "PERSISTENT_SESSION",
        class_name: "PersistentSessionWorkflow",
      },
    ],
    containers: [
      {
        name: "CodingContainer",
        image: "clawflare/container-runtime:latest",
      },
    ],
  };

  const configPath = path.join(projectDir, ".clawflare", "wrangler.jsonc");
  const output = `// Generated by Clawflare. Do not edit directly.
// Source of truth: clawflare.config.ts
${JSON.stringify(config, null, 2)}
`;

  await fs.mkdir(path.dirname(configPath), { recursive: true });
  await fs.writeFile(configPath, output);

  return configPath;
}

interface ConfigGenerateOptions {
  env?: string;
  output?: string;
}

interface ClawflareConfigFromProject {
  name: string;
  ai?: {
    provider?: string;
    model?: string;
  };
  cloudflare?: {
    compatibilityDate?: string;
    workerName?: string;
  };
}

async function loadConfig(projectDir: string): Promise<ClawflareConfigFromProject | null> {
  try {
    // Try to read clawflare.config.ts by evaluating it (simplified)
    const configPath = path.join(projectDir, "clawflare.config.ts");
    await fs.access(configPath);
    
    // For now, extract from package.json
    const pkgPath = path.join(projectDir, "package.json");
    const pkgContent = await fs.readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(pkgContent);
    return { name: pkg.name };
  } catch {
    return null;
  }
}

async function loadState(projectDir: string): Promise<Record<string, unknown> | null> {
  try {
    const statePath = path.join(projectDir, ".clawflare", "state.json");
    const content = await fs.readFile(statePath, "utf-8");
    return JSON.parse(content);
  } catch {
    return null;
  }
}

async function getCloudflareAccountId(): Promise<string | null> {
  try {
    const result = execSync("wrangler whoami", { encoding: "utf-8" });
    const match = result.match(/Account ID\s+([a-f0-9]+)/i);
    if (match) return match[1];

    // Try reading from .wrangler/config.json
    const configPath = path.join(process.env.HOME || "", ".wrangler", "config.json");
    try {
      const configContent = await fs.readFile(configPath, "utf-8");
      const config = JSON.parse(configContent);
      if (config.accounts && config.accounts.length > 0) {
        return config.accounts[0].id;
      }
    } catch {
      // Ignore errors reading config
    }

    return null;
  } catch {
    return null;
  }
}

/**
 * Generate command - creates the Wrangler configuration file
 */
export async function configGenerateCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Check for project structure
  const config = await loadConfig(cwd);
  if (!config) {
    console.error("Error: No Clawflare project found in current directory");
    console.error("Run 'clawflare init <name>' to create a new project");
    process.exit(1);
  }

  console.log(`Generating Wrangler config for "${config.name}"...`);

  // Load state
  const state = await loadState(cwd) || { version: 1 };

  // Get account ID
  const accountId = await getCloudflareAccountId();
  if (!state.cloudflare) {
    (state as Record<string, unknown>).cloudflare = {};
  }
  if (accountId) {
    ((state as Record<string, unknown>).cloudflare as Record<string, unknown>).accountId = accountId;
  }

  // Determine names
  const dbName = options.env ? `${config.name}-${options.env}` : config.name;
  const workerName = options.env ? `${config.name}-${options.env}` : config.name;
  const dbId = (state.cloudflare as Record<string, unknown>)?.d1DatabaseId as string | undefined;

  // Generate config
  const outputPath = options.output || path.join(cwd, ".clawflare", "wrangler.jsonc");
  const compatibilityDate = config.cloudflare?.compatibilityDate || "2025-01-01";

  const configPath = await generateWranglerConfig({
    projectDir: cwd,
    projectName: config.name,
    dbId,
    dbName,
    workerName,
    accountId: accountId || undefined,
    compatibilityDate,
  });

  console.log(`✓ Generated: ${configPath}`);
  console.log(`\nDatabase: ${dbName}`);
  console.log(`Worker: ${workerName}`);
  if (dbId) {
    console.log(`Database ID: ${dbId}`);
  } else {
    console.log(`Database ID: (not set - will be created on deploy)`);
  }
}

/**
 * Print command - displays the generated Wrangler configuration
 */
export async function configPrintCommand(options: ConfigGenerateOptions): Promise<void> {
  const cwd = process.cwd();

  // Check for project structure
  const config = await loadConfig(cwd);
  if (!config) {
    console.error("Error: No Clawflare project found in current directory");
    console.error("Run 'clawflare init <name>' to create a new project");
    process.exit(1);
  }

  // Load state
  const state = await loadState(cwd) || { version: 1 };

  // Get account ID
  const accountId = await getCloudflareAccountId();

  // Determine names
  const dbName = options.env ? `${config.name}-${options.env}` : config.name;
  const workerName = options.env ? `${config.name}-${options.env}` : config.name;
  const dbId = (state.cloudflare as Record<string, unknown>)?.d1DatabaseId as string | undefined;
  const compatibilityDate = config.cloudflare?.compatibilityDate || "2025-01-01";

  // Generate config (to temp path)
  await fs.mkdir(path.join(cwd, ".clawflare"), { recursive: true });
  const configPath = await generateWranglerConfig({
    projectDir: cwd,
    projectName: config.name,
    dbId,
    dbName,
    workerName,
    accountId: accountId || undefined,
    compatibilityDate,
  });

  // Read and display
  const content = await fs.readFile(configPath, "utf-8");
  console.log(content);
}

/**
 * Config command handler with subcommands
 */
export async function configCommand(
  subcommand: "generate" | "print",
  options: ConfigGenerateOptions
): Promise<void> {
  if (subcommand === "generate") {
    await configGenerateCommand(options);
  } else if (subcommand === "print") {
    await configPrintCommand(options);
  } else {
    console.error(`Unknown subcommand: ${subcommand}`);
    console.error("Available subcommands: generate, print");
    process.exit(1);
  }
}
